name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: gh-pages

    env:
      VITE_UNSPLASH_API_KEY: ${{ vars.VITE_UNSPLASH_API_KEY }}
      VITE_UNSPLASH_TOPIC: ${{ vars.VITE_UNSPLASH_TOPIC }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build the site
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
